'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Game_Zone.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_home_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-home-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_a_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_a_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_b_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_b_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_c_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_c_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_d_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_d_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_e_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_e_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_f_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_f_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_g_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_g_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_h_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_h_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_i_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_i_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_j_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_j_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_k_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_k_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_l_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_l_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_m_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_m_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_n_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_n_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_o_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_o_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_p_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_p_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_q_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_q_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_r_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_r_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_s_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_s_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_t_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_t_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_u_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_u_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_A_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_A_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_B_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_B_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_C_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_C_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_D_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_D_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_E_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_E_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_F_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_F_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_G_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_G_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_H_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_H_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_I_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_I_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_J_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_J_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_K_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_K_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_L_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_L_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_M_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_M_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_N_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_N_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_O_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_O_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_P_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_P_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_Q_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_Q_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_R_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_R_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_S_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_S_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_T_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_T_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_U_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_U_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_V_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_V_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_W_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_W_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_X_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_X_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_Y_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_Y_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_uppercase_Z_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_uppercase_Z_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_v_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_v_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_w_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_w_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_x_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_x_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_y_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_y_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_z_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_z_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property screen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property space() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("space", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
